spring:
  application:
    name: library-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/library
    username: library
    password: library
  liquibase:
    change-log: db/changelog/master.xml
    default-schema: public

server:
  port: 9090