version: '3.8'

services:
  app:
    container_name: library_app
    build:
      context: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library
      SPRING_DATASOURCE_USERNAME: library
      SPRING_DATASOURCE_PASSWORD: library
    ports:
      - "8080:8080"
    networks:
      - my_custom_network

  db:
    container_name: library_db
    image: postgres:15
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library
    ports:
      - "5432:5432"
    networks:
      - my_custom_network

networks:
  my_custom_network:
    name: library_network